name: Changelog generation

on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Run OpenAPI Diff (from HEAD revision)
        uses: evereepay/openapi-diff-action@v1.0.0-beta.1
        with:
          head-spec: branch.json
          base-spec: master.json
          
          
          