name: Changelog generation

on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          path: head

      - name: Checkout master
        uses: actions/checkout@v2
        with:
          ref: development
          path: base

      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14

      - name: Cache Gradle dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Generate branch OpenApi Spec
        run: cd head/ && ./gradlew task :generateOpenApiFile

      - name: Generate base OpenApi Spec
        run: cd base/ && ./gradlew task :generateOpenApiFile

      - name: Run OpenAPI Diff (from HEAD revision)
        uses: mvegter/openapi-diff-action@v0.23.3
        with:
          head-spec: head/build/resources/main/documentation/openapi.json
          base-spec: base/build/resources/main/documentation/openapi.json